### ISSUE TITLE
runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by zeyujiang** [NickyBoy89/java2go#4]
INFO[0000] Collecting files...                          
INFO[0000] Parsing ASTs...                              
INFO[0000] Generating symbol tables...                  
INFO[0000] Resolving symbols...                         
INFO[0000] Converting files...                          
INFO[0000] Converting file "FishersExact.java"          
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.GenMultiDimArray({0xc0001a4820, 0x5}, {0xc000199740, 0x0, 0xc0000a40a8?})
	.../generate.go:155 +0x1677
main.ParseExpr(0xc0001a9650, {0xc0000da000, 0x2aec, 0x2aed}, {{0xc0000ba130, 0xc}, 0xc000110e40, 0xc0000b60a0, 0xc0000e7d80, {0x0, ...}})
	.../expression.go:217 +0x5958
main.TryParseStmt(0xc0001a9560, {0xc0000da000, 0x2aec, 0x2aed}, {{0xc0000ba130, 0xc}, 0xc000110e40, 0xc0000b60a0, 0xc0000e7d80, {0x0, ...}})
	.../statement.go:107 +0x3035
main.TryParseStmt(0xc00010cf90, {0xc0000da000, 0x2aec, 0x2aed}, {{0xc0000ba130, 0xc}, 0xc000110e40, 0xc0000b60a0, 0xc0000e7d80, {0x0, ...}})
	.../statement.go:163 +0x2d7b
main.TryParseStmt(0xc00010cf30, {0xc0000da000, 0x2aec, 0x2aed}, {{0xc0000ba130, 0xc}, 0xc000110e40, 0xc0000b60a0, 0xc0000e7d80, {0x0, ...}})
	.../statement.go:154 +0x4b75
main.ParseStmt(0xc00010cf30, {0xc0000da000?, 0x2aec?, 0x2aed?}, {{0xc0000ba130, 0xc}, 0xc000110e40, 0xc0000b60a0, 0xc0000e7d80, {0x0, ...}})
	.../statement.go:15 +0x6e
main.ParseDecl(0xc00009a9c0, {0xc0000da000, 0x2aec, 0x2aed}, {{0xc0000ba130, 0xc}, 0xc000110e40, 0xc0000b60a0, 0xc0000e7d80, {0x0, ...}})
	.../declaration.go:317 +0x182a
main.ParseDecls(0xc00009a6c0, {0xc0000da000, 0x2aec, 0x2aed}, {{0xc0000ba130, 0xc}, 0xc000110e40, 0xc0000b60a0, 0x0, {0x0, ...}})
	.../declaration.go:106 +0x25cd
main.ParseDecls(0xc00009a5d0, {0xc0000da000, 0x2aec, 0x2aed}, {{0xc0000ba130, 0xc}, 0xc000110e40, 0xc0000b60a0, 0x0, {0x0, ...}})
	.../declaration.go:90 +0x1505
main.ParseNode(0xc00009a480, {0xc0000da000, 0x2aec, 0x2aed}, {{0x0, 0x0}, 0xc000110e40, 0xc0000b60a0, 0x0, {0x0, ...}})
	.../tree_sitter.go:89 +0x3425
main.main()
	.../java2go.go:224 +0xfa5

**Comment by NickyBoy89** [comment]
Hi, do you think you could provide a minimal reproducible example for this error?

**Comment by zeyujiang** [comment]
Hi, attached is the java source file that hit the bug. Best!
________________________________
